FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGthZmthLWFwYgpkZXNjcmlwdGlvbjogQVBCIGZvciBBcGFjaGUg\
S2Fma2EgYW5kIEFwYWNoZSBab29rZWVwZXIKYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25h\
bAptZXRhZGF0YToKICBkaXNwbGF5TmFtZTogQXBhY2hlIEthZmthIENsdXN0ZXIKICBjb25zb2xl\
Lm9wZW5zaGlmdC5pby9pY29uQ2xhc3M6IGZhIGZhLWVudmVsb3BlCnBsYW5zOgogIC0gbmFtZTog\
ZGVmYXVsdAogICAgZGVzY3JpcHRpb246IFRoaXMgZGVmYXVsdCBwbGFuIGRlcGxveXMga2Fma2Et\
YXBiCiAgICBmcmVlOiBUcnVlCiAgICBtZXRhZGF0YToge30KICAgIHBhcmFtZXRlcnM6IFtd"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
