- name: "Install barnabas kafka template"
  shell: "oc new-app -f https://raw.githubusercontent.com/EnMasseProject/barnabas/0.1.0-rc1/kafka-statefulsets/resources/openshift-template.yaml -n {{ namespace }}"
